### ISSUE TITLE
ValueError on png file when converting from obj to ply

### ISSUE THREAD

**Issue by KhaledSharif** [nabeel3133/.obj-to-.ply#1]
```
python3 convert.py --input ~/apr11_khaled/apr11/output/dense/texrecon.obj   --output ~/gascola.ply
/home/khaled/Repositories/file-converter-.obj-to-.ply/d3/model/formats/obj.py:58: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if splits[i][j] is not '':
Traceback (most recent call last):
  File "convert.py", line 126, in <module>
    PLYwithRGB(objFile,plyFile)
  File "convert.py", line 48, in PLYwithRGB
    vertex_count = int(VertList[2])
ValueError: invalid literal for int() with base 10: 'texrecon_material0000_map_Kd.png'
```

**Comment by nabeel3133** [comment]
Hello there!
Thank you for checking out the repository. Can you kindly make sure if your .obj file does not contain any vertex textures and vertex normals? The code only works for .obj files containing vertices along with vertex colors and faces.
